### ISSUE TITLE
Adding modifiers to a range of days

### ISSUE THREAD

**Issue by gpbl** [freiksenet/react-calendar#11]
Hi, first of all thank you for this awesome component. I got my datepicker working :+1: 

In my use case, I am showing the current month. 
I need to add a modifier to the days *before the current day* – they should appear as "disabled".

I was thinking to add an array of `<Day/>`, from the month's first to the current day – but I'm not sure how to match the days belonging to the previous month, when they appear as *outside*.

Suggestions?

Another idea is to have a `<DaysRange/>` component, e.g:

```xml
<DaysRange before={moment()} modifier={{past: true}} /> 
<DaysRange after={moment()}  modifier={{future: true}}  />
<DaysRange before={moment('12/10/2014')} after={moment('12/01/2014')} />
```

**Comment by srconklin** [comment]
I am also in need of random sets of dates highlighted on the calendar. 
Any progress on this?

**Comment by freiksenet** [comment]
I'll try to get around to my open source stuff at the end of this week.

**Comment by lolJS** [comment]
@gpbl With the new API you should be able to pass `startDate` and `endDate` params in your modifier object:

ex:

```javascript
<Calendar weekNumbers={ true }
                  startDate={ this.state.date }
                  endDate={ this.state.date.clone().endOf('year') }
                  mods={
                  [
                    {
                      startDate: moment().add(3, 'days'),
                      endDate: moment().add(7, 'days'),
                      classNames: [ 'longEvent' ],
                      component: [ 'day' ]
                    }
                  ]
                } />
```

**Comment by gpbl** [comment]
Thanks! Time runs fast, so I've built [an alternative](https://github.com/gpbl/react-day-picker) that was helping my use case.
