### ISSUE TITLE
Compatibility with react 0.13

### ISSUE THREAD

**Issue by vivian-perez** [freiksenet/react-calendar#18]
Have you forecast to be comptible with react 0.13.
If yes, when ?
Thanks

**Comment by freiksenet** [comment]
Hi!

It's currently on hiatus, because I am very busy with other projects. I'll get back to it eventually, but pull requests are very welcome, I am sure upgrading to 0.13 wouldn't be a big issue, I am here to help if you decide to work on that.
 
Cheers,
Mikhail

**Comment by ericwooley** [comment]
How do you develop on this? I forked and can't get anything to run unless it's on the gh-pages branch. I ran npm start and all I get is a console error saying that module is not defined.

What is your setup like?

**Comment by freiksenet** [comment]
Seems that bootstrap (that's used for the example) has broken the build with newer version, you can force the version to 3.2.0 to make it work.

```
npm install bootstrap@3.2.0
```

Otherwise `npm install` and `npm start` will launch webpack dev server.
