### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by ericwooley** [freiksenet/react-calendar#20]
We wanted to use this in a project, however the render time is too long (noticeable lag). There is a lot of loops and cloning moment going on. It might be worth looking into reducing the render times.

**Comment by freiksenet** [comment]
Agreed.

One 'low-hanging fruit' could be replacing the keys that I (wrongly) assigned to unique ids to simple positional ones, that would reduce re-render time, I think.

**Comment by lolJS** [comment]
@ericwooley could you check out the latest master branch and let me know if it's solved your performance issues?

**Comment by lolJS** [comment]
Also closing this issue! :alien:

**Comment by ericwooley** [comment]
Sorry just saw this.

Unfortunately  i don't have the source code anymore to check how it renders. Glad you got it lowered though!
