### ISSUE TITLE
First Week of Month Shows on Previous Month

### ISSUE THREAD

**Issue by lolJS** [freiksenet/react-calendar#30]
When the date is March 1, the overflow from February shows the current week / day.

**Comment by lolJS** [comment]
@freiksenet When I close this bug we should do a review and then push a new release to npm and gh-pages.

**Comment by freiksenet** [comment]
@lolJS What's your npm username? I'll add you to package collaborators.

**Comment by lolJS** [comment]
@freiksenet Thanks, it's [anoobis](https://www.npmjs.com/~anoobis).

**Comment by freiksenet** [comment]
Done.
