### ISSUE TITLE
Warning: date is required in Month Check the render method of ...

### ISSUE THREAD

**Issue by fson** [freiksenet/react-calendar#6]
Because `date` is required in both `propTypes` and `contextTypes`, a warning is shown even if you pass it in as a prop. Example:
```js
var DatePicker = React.createClass({
  render() {
    return <Month date={moment()} />
  }
});
```
Prints `Warning: date is required in Month Check the render method of DatePicker.` in the console.

**Comment by philschatz** [comment]
:+1:
